# SPDX-License-Identifier: Apache-2.0
"""Board-side PIO + DMA sample capture for the Tiny Tapeout demo board.

MicroPython, run by the host via `RawRepl.exec_stream()` with a `CFG` dict
prepended by `ttcap.mp.with_cfg()`. Keys:

    clk_gpio     GPIO carrying the project clock (rp_projclk)
    in_base      first uo_out GPIO; the PIO input window starts here
    in_count     bits sampled per clock edge (12 on RP2040, 8 on RP2350)
    gpio_base    PIO GPIO base: 0, or 16 on RP2350 where uo_out is GPIO 33+
    push_thresh  autopush threshold in bits: 24 for 12-bit x2, 32 for 8-bit x4
    buf_words    32-bit words per DMA buffer (two are allocated), e.g. 4096
    max_bytes    stop after this many emitted bytes; 0 = run until Ctrl-C
    edge         "falling" (default) or "rising" project-clock edge to sample
    pio          PIO block index; 1 by default, *not* 0 -- the stock
                 firmware keeps its own program (the FPGA loader) in PIO0,
                 which on RP2350 also blocks moving that block's pin window
    sm           state machine index within that block (0)
    sysclk_hz    informational; the capture never changes the system clock

Output: this script emits **only** `RAW ` and `TIME` chunks. The `VGCH`
stream header is written by the host (`vgacap.stream.Writer`), which knows
the signal map, mode and clock; everything this script writes is appended
after it verbatim.

Sampling: the project clock is generated by the RP2040/RP2350 itself, so the
sampler is purely a slave. The state machine spins at full system clock,
waits for the clock line to go high and then low (the falling edge, by which
time the project outputs have settled), samples the input window, and wraps.
For `edge == "rising"` the two waits are swapped.

Bit packing -- why the ISR shifts LEFT. The PIO always pushes all 32 ISR
bits; only the shift *counter* is compared against the autopush threshold
(RP2040 datasheet 3.4.4 IN, 3.5.4 autopush). Shifting left, data enters at
the LSB end and earlier samples move toward the MSB, so after
`samples_per_word` samples the word is right-aligned with sample 0 in the
top occupied slot: for 12-bit x2, samples 0xABC and 0x123 pack to
0x00ABC123. That is exactly `sample_bits=12, samples_per_word=2,
flags=VGACAP_FLAG_FIRST_SAMPLE_MSB`, the header the host writes, and it
holds for 8-bit x4 at threshold 32 too. Shifting right would leave the
12-bit pair in bits 31:8 -- left-justified, which no `flags` value can
express and which `vgacap.stream.unpack_words()` cannot decode.

Constants inside a PIO program must be closure variables, not module
globals: `rp2.asm_pio` clears the decorated function's `__globals__` for the
duration of its two assembly passes and installs only the instruction
mnemonics (micropython v1.24.0 ports/rp2/modules/rp2.py:257-259), so a
`LOAD_GLOBAL` of a CFG-derived name raises NameError on the board. Hence
`make_sampler()` below: its parameters become cells, which `LOAD_DEREF`
reaches regardless of the globals swap.

Registers (pico-sdk `addressmap.h`, `hardware/structs/pio.h`, `dreq.h`,
`hardware/structs/dma.h`; the host mirrors the PIO arithmetic in
`ttcap.boards.rxf_addr`/`rx_dreq`):

    PIO block base   0x50200000 + 0x100000 * pio
                     RP2040: PIO0 0x50200000, PIO1 0x50300000
                     RP2350: adds PIO2 0x50400000 -- same formula
    RXFn             base + 0x20 + 4 * sm     (the DMA read address)
    FDEBUG           base + 0x08              (RXSTALL = bits 0..3, W1C)
    RX DREQ          8 * pio + 4 + sm         (TX DREQs are 8 * pio + sm)

    DMA block base   0x50000000, channel stride 0x40
    CHn_READ_ADDR    + 0x00        CHn_WRITE_ADDR   + 0x04
    CHn_TRANS_COUNT  + 0x08        CHn_CTRL_TRIG    + 0x0c   (writing this
                                                              STARTS the
                                                              channel)
    CHn_AL1_CTRL     + 0x10 ... CHn_AL1_TRANS_COUNT_TRIG + 0x1c
    Only the two non-trigger aliases at +0x04 and +0x08 are written, so a
    re-arm never starts a channel; the partner's chain does that. The
    offsets are self-checked at run time against the address MicroPython's
    `DMA.config(write=...)` programmed.

DMA: two channels ping-pong into two buffers, each chained to the other, so
the PIO never stalls while the main loop is writing a buffer out over USB.
The chain re-triggers a channel but reloads neither its write address nor
its transfer count, so each channel's own completion IRQ re-arms it -- from
the hard IRQ, before its partner can finish, which is what makes the handoff
race-free. There is therefore at most one buffer of latency. If a handler
finds its buffer still marked full, the main loop did not consume it in
time: the DMA is now overwriting data the host never saw. That is counted
as an overrun and reported in a `TIME` chunk with
`dropped_samples = overruns * buf_words * samples_per_word`. `FDEBUG`'s
RXSTALL bit is cleared at the start and read back at the end -- if it is
set, the RX FIFO overflowed and samples were lost regardless.

The raw REPL terminates stdout with a 0x04 byte and does not escape the
payload, so a host that scans for 0x04 stops early. Every chunk is
`4-byte tag + u32 length + payload` and nothing else is printed, so the
host reads length-driven instead (`ttcap.repl.RawRepl.exec_chunks`).

The project clock pad is never configured here. Driving it through
`machine.Pin(clk, Pin.IN)` takes the pad away from the firmware's PWM and
stops the clock outright, and the PIO's `wait gpio` reads the pad's input
synchroniser whatever its FUNCSEL is -- see `init_input_pins()`.
"""

import machine
import rp2
import sys
import uctypes

CLK_GPIO = CFG["clk_gpio"]  # noqa: F821 - CFG is prepended by the host
IN_BASE = CFG["in_base"]  # noqa: F821
IN_COUNT = CFG["in_count"]  # noqa: F821
GPIO_BASE = CFG["gpio_base"]  # noqa: F821
PUSH_THRESH = CFG["push_thresh"]  # noqa: F821
BUF_WORDS = CFG["buf_words"]  # noqa: F821
MAX_BYTES = CFG["max_bytes"]  # noqa: F821
EDGE = CFG["edge"]  # noqa: F821
PIO_NUM = CFG["pio"]  # noqa: F821
SM_NUM = CFG["sm"]  # noqa: F821
SYSCLK_HZ = CFG["sysclk_hz"]  # noqa: F821 - informational

# The PIO assembler cannot know which block the program will run on, so it
# emits the WAIT GPIO index verbatim and the hardware adds the block's
# GPIOBASE to it. The index must therefore be relative to GPIO_BASE: on
# RP2040 GPIOBASE is always 0 and this is just clk_gpio; on RP2350 the whole
# 32-pin window starts at GPIO 16.
CLK_PIO_INDEX = CLK_GPIO - GPIO_BASE

SAMPLES_PER_WORD = PUSH_THRESH // IN_COUNT
BUF_BYTES = 4 * BUF_WORDS
SAMPLES_PER_CHUNK = BUF_WORDS * SAMPLES_PER_WORD

PIO_BASE = 0x50200000 + 0x100000 * PIO_NUM
RXF_ADDR = PIO_BASE + 0x20 + 4 * SM_NUM
FDEBUG_ADDR = PIO_BASE + 0x8
RXSTALL_BIT = 1 << SM_NUM
DREQ = 8 * PIO_NUM + 4 + SM_NUM

DMA_BASE = 0x50000000
DMA_CH_STRIDE = 0x40
DMA_CH_WRITE_ADDR = 0x04
DMA_CH_TRANS_COUNT = 0x08


def _le32(value):
    """Pack `value` as a little-endian uint32."""
    return bytes(
        (
            value & 0xFF,
            (value >> 8) & 0xFF,
            (value >> 16) & 0xFF,
            (value >> 24) & 0xFF,
        )
    )


def _write_all(out, data):
    """Write every byte of `data` to `out`, tolerating short writes."""
    pos = 0
    n = len(data)
    while pos < n:
        written = out.write(data[pos:] if pos else data)
        if written is None:
            return n
        pos += written
    return n


def write_raw_chunk(out, buf, sample_count):
    """Emit one `RAW ` chunk and return the number of bytes written."""
    written = _write_all(out, b"RAW " + _le32(4 + len(buf)) + _le32(sample_count))
    return written + _write_all(out, buf)


def write_time_chunk(out, dropped_samples, msg):
    """Emit one `TIME` chunk and return the number of bytes written.

    `host_time_ns` and `clock_hz` are zero: the board has no host clock and
    the host already recorded the project clock in the stream header.
    """
    payload = (
        _le32(0)
        + _le32(0)  # u64 host_time_ns = 0
        + _le32(0)  # u32 clock_hz = 0
        + _le32(dropped_samples)
        + bytes((len(msg) & 0xFF, (len(msg) >> 8) & 0xFF))
        + msg
    )
    return _write_all(out, b"TIME" + _le32(len(payload)) + payload)


def dma_reg(channel, offset):
    """Absolute address of one register of DMA channel `channel`."""
    return DMA_BASE + DMA_CH_STRIDE * channel + offset


def init_input_pins(pin_cls, in_base, in_count):
    """Bring every sampled pad up as a plain input -- never the clock pad.

    RP2350 pads come out of reset with `PADS_BANK0_GPIOn.ISO` set, and
    MicroPython calls `pio_gpio_init()` only for out/set/sideset pins, so an
    untouched `in_base` pad would read 0 forever and the capture would be
    silently all-zero with no RXSTALL to warn you. A bare `machine.Pin(n)`
    with no mode does not touch the hardware; passing a mode does. No pulls:
    the project drives these lines.

    The clock pad is deliberately left alone. `machine.Pin(clk, Pin.IN)`
    switches its FUNCSEL from PWM to SIO, which *stops* the clock the
    firmware's `tt.clock_project_PWM()` is generating -- measured on fpga-1:
    after this ran, GPIO16 read 0 in 32 consecutive samples and the state
    machine sat in its `wait` forever, so not one chunk was ever emitted.
    The PIO samples a pad's input synchroniser whatever its FUNCSEL is, so
    `wait gpio` needs no pad setup at all.
    """
    for gpio in range(in_base, in_base + in_count):
        pin_cls(gpio, pin_cls.IN)


def make_sampler(clk_index, in_count, push, rising):
    """Assemble the sampler program with its operands as closure cells.

    `clk_index` and `in_count` are read inside the program body, so they
    must be cells (`LOAD_DEREF`) rather than module globals: `asm_pio`
    clears `__globals__` while it assembles. `push` is only a decorator
    argument, evaluated before that happens.
    """
    if rising:

        @rp2.asm_pio(
            in_shiftdir=rp2.PIO.SHIFT_LEFT,
            autopush=True,
            push_thresh=push,
            fifo_join=rp2.PIO.JOIN_RX,
        )
        def sampler():
            wrap_target()  # noqa: F821 - PIO assembler directives
            wait(0, gpio, clk_index)  # noqa: F821
            wait(1, gpio, clk_index)  # noqa: F821 - rising edge
            in_(pins, in_count)  # noqa: F821
            wrap()  # noqa: F821

    else:

        @rp2.asm_pio(
            in_shiftdir=rp2.PIO.SHIFT_LEFT,
            autopush=True,
            push_thresh=push,
            fifo_join=rp2.PIO.JOIN_RX,
        )
        def sampler():
            wrap_target()  # noqa: F821
            wait(1, gpio, clk_index)  # noqa: F821
            wait(0, gpio, clk_index)  # noqa: F821 - falling: outputs settled
            in_(pins, in_count)  # noqa: F821
            wrap()  # noqa: F821

    return sampler


def gpio_base_is(pio, want):
    """True when PIO block `pio` already has its 32-pin window at `want`.

    `PIO.gpio_base()` with no argument returns a *Pin*, not an int
    (micropython ports/rp2/rp2_pio.c: `return pio_get_gpio_base(self->pio)
    == 0 ? pin_GPIO0 : pin_GPIO16`), so there is nothing to compare
    numerically. rp2 `Pin` objects come from one static table, so
    `is machine.Pin(want)` would likely work too, but the repr check is
    what was verified on fpga-1 and it does not depend on `pin_GPIOn` and
    `machine_pin_obj_table[n]` being the same objects.
    """
    return str(pio.gpio_base()).startswith("Pin(GPIO" + str(want) + ",")


def main(out):
    """Run the sampler, streaming RAW chunks to `out` until told to stop."""
    if GPIO_BASE:
        # RP2350 only, and it must happen before the state machine exists:
        # it shifts the whole PIO block's 32-pin window up to GPIO 16..47.
        #
        # Only when it is not already there: pico-sdk's
        # `pio_set_gpio_base_unsafe()` returns PICO_ERROR_INVALID_STATE (an
        # OSError EINVAL here) whenever the block's instruction memory is in
        # use, and on the stock firmware every block is -- PIO0 holds the
        # FPGA loader, and PIO1/PIO2 hold programs of their own but already
        # sit at base 16, so for them the move is a no-op that only needs
        # skipping. Measured on fpga-1, firmware 3.1.0.
        block = rp2.PIO(PIO_NUM)
        if not gpio_base_is(block, GPIO_BASE):
            try:
                block.gpio_base(GPIO_BASE)
            except Exception:
                pass
            if not gpio_base_is(block, GPIO_BASE):
                write_time_chunk(
                    out,
                    0,
                    (
                        "error=PIO"
                        + str(PIO_NUM)
                        + " gpio_base is not "
                        + str(GPIO_BASE)
                        + " and cannot be moved (instruction memory in use);"
                        + " try another pio block"
                    ).encode(),
                )
                return

    init_input_pins(machine.Pin, IN_BASE, IN_COUNT)

    sampler = make_sampler(CLK_PIO_INDEX, IN_COUNT, PUSH_THRESH, EDGE == "rising")
    sm = rp2.StateMachine(PIO_NUM * 4 + SM_NUM, sampler, in_base=machine.Pin(IN_BASE))

    bufs = [bytearray(BUF_BYTES), bytearray(BUF_BYTES)]
    full = [False, False]
    overruns = [0]
    in_flight = [False]
    dma_a = None
    dma_b = None

    try:
        dma_a = rp2.DMA()
        dma_b = rp2.DMA()
        dmas = [dma_a, dma_b]

        ctrl_a = dma_a.pack_ctrl(
            size=2,
            inc_read=False,
            inc_write=True,
            treq_sel=DREQ,
            chain_to=dma_b.channel,
            irq_quiet=False,
        )
        ctrl_b = dma_b.pack_ctrl(
            size=2,
            inc_read=False,
            inc_write=True,
            treq_sel=DREQ,
            chain_to=dma_a.channel,
            irq_quiet=False,
        )
        dma_a.config(read=RXF_ADDR, write=bufs[0], count=BUF_WORDS, ctrl=ctrl_a, trigger=False)
        dma_b.config(read=RXF_ADDR, write=bufs[1], count=BUF_WORDS, ctrl=ctrl_b, trigger=False)

        mem = machine.mem32
        wr_a = dma_reg(dma_a.channel, DMA_CH_WRITE_ADDR)
        wr_b = dma_reg(dma_b.channel, DMA_CH_WRITE_ADDR)
        tc_a = dma_reg(dma_a.channel, DMA_CH_TRANS_COUNT)
        tc_b = dma_reg(dma_b.channel, DMA_CH_TRANS_COUNT)
        addr_a = uctypes.addressof(bufs[0])
        addr_b = uctypes.addressof(bufs[1])

        # Self-check the register map before anything can run: config() has
        # just programmed these two write addresses, so if the offsets were
        # wrong the re-arm below would point the DMA at arbitrary memory.
        if mem[wr_a] != addr_a or mem[wr_b] != addr_b:
            write_time_chunk(out, 0, b"error=dma write-addr register offset mismatch")
            return

        def on_a(_channel):
            # Re-arm channel A first: its partner's chain re-triggers it the
            # moment B completes, which can be long before the main loop
            # gets back here. Both are non-trigger aliases, so this arms the
            # channel without starting it.
            mem[wr_a] = addr_a
            mem[tc_a] = BUF_WORDS
            if full[0]:
                overruns[0] += 1
            full[0] = True

        def on_b(_channel):
            mem[wr_b] = addr_b
            mem[tc_b] = BUF_WORDS
            if full[1]:
                overruns[0] += 1
            full[1] = True

        dma_a.irq(on_a, hard=True)
        dma_b.irq(on_b, hard=True)

        mem[FDEBUG_ADDR] = RXSTALL_BIT  # write-1-to-clear a stale stall

        # Arm the DMA before the state machine, so the first samples cannot
        # stall the RX FIFO during the call overhead between the two.
        dma_a.active(1)
        sm.active(1)

        sent = 0
        reported = 0
        index = 0
        while True:
            while not full[index]:
                machine.idle()
            in_flight[0] = True
            sent += write_raw_chunk(out, bufs[index], SAMPLES_PER_CHUNK)
            in_flight[0] = False
            full[index] = False
            if overruns[0] > reported:
                dropped = (overruns[0] - reported) * SAMPLES_PER_CHUNK
                sent += write_time_chunk(out, dropped, b"overrun")
                reported = overruns[0]
            index = 1 - index
            if MAX_BYTES and sent >= MAX_BYTES:
                break
    except KeyboardInterrupt:
        pass
    finally:
        overrun_total = overruns[0]
        rxstall = (machine.mem32[FDEBUG_ADDR] >> SM_NUM) & 1
        # Drop the IRQ handlers before aborting: an abort can raise a
        # spurious completion IRQ (and on RP2350, errata RP2350-E5, a chain
        # partner can re-trigger the aborted channel), which would inflate
        # the overrun count that was just snapshotted.
        for dma in (dma_a, dma_b):
            if dma is not None:
                dma.irq(None)
        sm.active(0)
        for dma in (dma_a, dma_b):
            if dma is not None:
                dma.active(0)
        for dma in (dma_a, dma_b):
            if dma is not None:
                dma.close()
        if not in_flight[0]:
            # A chunk interrupted mid-write would leave the stream desynced;
            # appending a trailer after it only makes that worse.
            summary = (
                "overruns="
                + str(overrun_total)
                + " rxstall="
                + str(rxstall)
                + " sysclk_hz="
                + str(machine.freq())
            )
            write_time_chunk(out, overrun_total * SAMPLES_PER_CHUNK, summary.encode())
        if hasattr(out, "flush"):
            out.flush()


_OUT = sys.stdout.buffer
if not hasattr(rp2, "DMA"):
    write_time_chunk(_OUT, 0, b"error=rp2.DMA missing, needs MicroPython >= 1.22")
elif GPIO_BASE and not hasattr(rp2.PIO, "gpio_base"):
    write_time_chunk(_OUT, 0, b"error=PIO.gpio_base missing, needs MicroPython >= 1.24")
else:
    main(_OUT)
