# SPDX-License-Identifier: Apache-2.0
"""Board-side PIO + DMA sample capture for the Tiny Tapeout demo board.

MicroPython, run by the host via `RawRepl.exec_stream()` with a `CFG` dict
prepended by `ttcap.mp.with_cfg()`. Keys:

    clk_gpio     GPIO carrying the project clock (rp_projclk)
    in_base      first uo_out GPIO; the PIO input window starts here
    in_count     bits sampled per clock edge (12 on RP2040, 8 on RP2350)
    gpio_base    PIO GPIO base: 0, or 16 on RP2350 where uo_out is GPIO 33+
    push_thresh  autopush threshold in bits: 24 for 12-bit x2, 32 for 8-bit x4
    buf_words    32-bit words per DMA buffer (two are allocated), e.g. 4096
    max_bytes    stop after this many emitted bytes; 0 = run until Ctrl-C
    edge         "falling" (default) or "rising" project-clock edge to sample
    pio          PIO block index (0)
    sm           state machine index within that block (0)
    sysclk_hz    informational; the capture never changes the system clock

Output: this script emits **only** `RAW ` and `TIME` chunks. The `VGCH`
stream header is written by the host (`vgacap.stream.Writer`), which knows
the signal map, mode and clock; everything this script writes is appended
after it verbatim.

Sampling: the project clock is generated by the RP2040/RP2350 itself, so the
sampler is purely a slave. The state machine spins at full system clock,
waits for the clock line to go high and then low (the falling edge, by which
time the project outputs have settled), samples the input window, and wraps.
With SHIFT_RIGHT and an autopush threshold of `push_thresh`, sample 0 lands
in the low bits of the FIFO word and later samples above it -- exactly the
`samples_per_word = push_thresh // in_count`, `flags = 0` layout the host
writes into the header. For `edge == "rising"` the two waits are swapped.

Registers (pico-sdk `addressmap.h`, `hardware/structs/pio.h`, `dreq.h`; the
host mirrors this arithmetic in `ttcap.boards.rxf_addr`/`rx_dreq`):

    PIO block base   0x50200000 + 0x100000 * pio
                     RP2040: PIO0 0x50200000, PIO1 0x50300000
                     RP2350: adds PIO2 0x50400000 -- same formula
    RXFn             base + 0x20 + 4 * sm     (the DMA read address)
    FDEBUG           base + 0x08              (RXSTALL = bits 0..3, W1C)
    RX DREQ          8 * pio + 4 + sm         (TX DREQs are 8 * pio + sm)

DMA: two channels ping-pong into two buffers, each chained to the other, so
the PIO never stalls while the main loop is writing a buffer out over USB.
A per-channel hard IRQ marks "this buffer is full"; the main loop writes that
buffer as a `RAW ` chunk, then re-arms the channel (the chain re-triggers a
channel but does not reload its write address or transfer count). If a hard
IRQ finds its buffer still marked full, the main loop did not keep up: that
is counted as an overrun and reported in a `TIME` chunk. `FDEBUG`'s RXSTALL
bit is cleared at the start and read back at the end -- if it is set, the RX
FIFO overflowed and samples were lost regardless of the overrun count.

Known limitation: the raw REPL terminates stdout with a 0x04 byte and does
not escape the payload, so a 0x04 inside a chunk ends the host's read early.
See the report for milestone-3 tasks 2-3.
"""

import machine
import rp2
import sys

CLK_GPIO = CFG["clk_gpio"]  # noqa: F821 - CFG is prepended by the host
IN_BASE = CFG["in_base"]  # noqa: F821
IN_COUNT = CFG["in_count"]  # noqa: F821
GPIO_BASE = CFG["gpio_base"]  # noqa: F821
PUSH_THRESH = CFG["push_thresh"]  # noqa: F821
BUF_WORDS = CFG["buf_words"]  # noqa: F821
MAX_BYTES = CFG["max_bytes"]  # noqa: F821
EDGE = CFG["edge"]  # noqa: F821
PIO_NUM = CFG["pio"]  # noqa: F821
SM_NUM = CFG["sm"]  # noqa: F821
SYSCLK_HZ = CFG["sysclk_hz"]  # noqa: F821 - informational

# The PIO assembler cannot know which block the program will run on, so it
# emits the WAIT GPIO index verbatim and the hardware adds the block's
# GPIOBASE to it. The index must therefore be relative to GPIO_BASE: on
# RP2040 GPIOBASE is always 0 and this is just clk_gpio; on RP2350 the whole
# 32-pin window starts at GPIO 16.
CLK_PIO_INDEX = CLK_GPIO - GPIO_BASE

SAMPLES_PER_WORD = PUSH_THRESH // IN_COUNT
BUF_BYTES = 4 * BUF_WORDS
SAMPLES_PER_CHUNK = BUF_WORDS * SAMPLES_PER_WORD

PIO_BASE = 0x50200000 + 0x100000 * PIO_NUM
RXF_ADDR = PIO_BASE + 0x20 + 4 * SM_NUM
FDEBUG_ADDR = PIO_BASE + 0x8
RXSTALL_BIT = 1 << SM_NUM
DREQ = 8 * PIO_NUM + 4 + SM_NUM

# Chunk sizes, for the max_bytes accounting: 8-byte tag+length header plus
# payload (RAW: u32 sample_count + the buffer; TIME: 18 + len(msg)).
RAW_CHUNK_BYTES = 8 + 4 + BUF_BYTES


def _le32(value):
    """Pack `value` as a little-endian uint32."""
    return bytes(
        (
            value & 0xFF,
            (value >> 8) & 0xFF,
            (value >> 16) & 0xFF,
            (value >> 24) & 0xFF,
        )
    )


def _write_all(out, data):
    """Write every byte of `data` to `out`, tolerating short writes."""
    pos = 0
    n = len(data)
    while pos < n:
        written = out.write(data[pos:] if pos else data)
        if written is None:
            return
        pos += written


def write_raw_chunk(out, buf, sample_count):
    """Emit one `RAW ` chunk: tag, u32 payload length, u32 samples, words."""
    _write_all(out, b"RAW " + _le32(4 + len(buf)) + _le32(sample_count))
    _write_all(out, buf)


def write_time_chunk(out, dropped_samples, msg):
    """Emit one `TIME` chunk carrying a dropped-sample count and a message.

    `host_time_ns` and `clock_hz` are zero: the board has no host clock and
    the host already recorded the project clock in the stream header.
    """
    payload = (
        _le32(0)
        + _le32(0)  # u64 host_time_ns = 0
        + _le32(0)  # u32 clock_hz = 0
        + _le32(dropped_samples)
        + bytes((len(msg) & 0xFF, (len(msg) >> 8) & 0xFF))
        + msg
    )
    _write_all(out, b"TIME" + _le32(len(payload)) + payload)


# `rp2.asm_pio` evaluates its arguments and assembles the program when the
# `def` executes, so PUSH_THRESH / CLK_PIO_INDEX / IN_COUNT must already be
# bound -- which they are: they are module globals assigned from CFG above.
if EDGE == "falling":

    @rp2.asm_pio(
        in_shiftdir=rp2.PIO.SHIFT_RIGHT,
        autopush=True,
        push_thresh=PUSH_THRESH,
        fifo_join=rp2.PIO.JOIN_RX,
    )
    def sampler():
        wrap_target()  # noqa: F821 - PIO assembler directives
        wait(1, gpio, CLK_PIO_INDEX)  # noqa: F821
        wait(0, gpio, CLK_PIO_INDEX)  # noqa: F821 - falling: outputs settled
        in_(pins, IN_COUNT)  # noqa: F821
        wrap()  # noqa: F821

else:

    @rp2.asm_pio(
        in_shiftdir=rp2.PIO.SHIFT_RIGHT,
        autopush=True,
        push_thresh=PUSH_THRESH,
        fifo_join=rp2.PIO.JOIN_RX,
    )
    def sampler():
        wrap_target()  # noqa: F821
        wait(0, gpio, CLK_PIO_INDEX)  # noqa: F821
        wait(1, gpio, CLK_PIO_INDEX)  # noqa: F821 - rising edge
        in_(pins, IN_COUNT)  # noqa: F821
        wrap()  # noqa: F821


def main(out):
    """Run the sampler, streaming RAW chunks to `out` until told to stop."""
    if GPIO_BASE:
        # RP2350 only, and it must happen before the state machine exists:
        # it shifts the whole PIO block's 32-pin window up to GPIO 16..47.
        rp2.PIO(PIO_NUM).gpio_base(GPIO_BASE)

    sm = rp2.StateMachine(PIO_NUM * 4 + SM_NUM, sampler, in_base=machine.Pin(IN_BASE))

    bufs = [bytearray(BUF_BYTES), bytearray(BUF_BYTES)]
    full = [False, False]
    overruns = [0]

    dma_a = rp2.DMA()
    dma_b = rp2.DMA()
    dmas = [dma_a, dma_b]

    def on_a(_channel):
        if full[0]:
            overruns[0] += 1
        full[0] = True

    def on_b(_channel):
        if full[1]:
            overruns[0] += 1
        full[1] = True

    ctrl_a = dma_a.pack_ctrl(
        size=2,
        inc_read=False,
        inc_write=True,
        treq_sel=DREQ,
        chain_to=dma_b.channel,
        irq_quiet=False,
    )
    ctrl_b = dma_b.pack_ctrl(
        size=2,
        inc_read=False,
        inc_write=True,
        treq_sel=DREQ,
        chain_to=dma_a.channel,
        irq_quiet=False,
    )
    dma_a.config(read=RXF_ADDR, write=bufs[0], count=BUF_WORDS, ctrl=ctrl_a, trigger=False)
    dma_b.config(read=RXF_ADDR, write=bufs[1], count=BUF_WORDS, ctrl=ctrl_b, trigger=False)
    dma_a.irq(on_a, hard=True)
    dma_b.irq(on_b, hard=True)

    machine.mem32[FDEBUG_ADDR] = RXSTALL_BIT  # write-1-to-clear a stale stall

    sm.active(1)
    dma_a.active(1)

    sent = 0
    reported = 0
    index = 0
    try:
        while True:
            while not full[index]:
                machine.idle()
            write_raw_chunk(out, bufs[index], SAMPLES_PER_CHUNK)
            sent += RAW_CHUNK_BYTES
            full[index] = False
            # The chain re-triggers this channel when its partner finishes,
            # but neither the write address nor the transfer count reloads.
            dmas[index].config(write=bufs[index], count=BUF_WORDS, trigger=False)
            if overruns[0] > reported:
                dropped = (overruns[0] - reported) * SAMPLES_PER_CHUNK
                write_time_chunk(out, dropped, b"overrun")
                sent += 8 + 18 + 7
                reported = overruns[0]
            index = 1 - index
            if MAX_BYTES and sent >= MAX_BYTES:
                break
    except KeyboardInterrupt:
        pass

    sm.active(0)
    dma_a.active(0)
    dma_b.active(0)
    rxstall = (machine.mem32[FDEBUG_ADDR] >> SM_NUM) & 1
    dma_a.close()
    dma_b.close()

    summary = "overruns=" + str(overruns[0]) + " rxstall=" + str(rxstall)
    write_time_chunk(out, overruns[0] * SAMPLES_PER_CHUNK, summary.encode())


main(sys.stdout.buffer)
